services:
  - type: web
    name: jusas
    runtime: docker
    repo: https://github.com/reybien29/jusas
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Jusas
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-east-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.orlxefxqijqmvplsmivf
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_PG_EMULATE_PREPARES
        value: "false"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: FILESYSTEM_DISK
        value: local
